name: clean_code
description: a clean code base
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.3.1

dependencies:
  flutter:
    sdk: flutter
  # flutter_localizations:
  #   sdk: flutter
  intl: ^0.19.0
  flutter_riverpod: ^2.1.0
  dio: ^5.5.0+1
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  logger: ^2.4.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  # very_good_analysis: 

flutter:
  uses-material-design: true
  generate: true
